[package]
name = "ffms2"
version = "0.1.0"
authors = ["Luni-4 <luni-4@hotmail.it>"]
description = "FFI bindings to ffms2"
repository = "https://github.com/rust-av/ffms2-rs"
edition = "2018"
license = "MIT"

[dependencies]
ffms2-sys = { path = "ffms2-sys" }
cfg-if = "0.1"
paste = "1.0"

[dev-dependencies]
structopt = "0.3"

[features]
ffms2-2-15-3 = []
ffms2-2-15-4 = ["ffms2-2-15-3"]
ffms2-2-17-1 = ["ffms2-2-15-4"]
ffms2-2-21-0 = ["ffms2-2-17-1"]
ffms2-2-24-0 = ["ffms2-2-21-0"]
ffms2-2-27-0 = ["ffms2-2-24-0"]
ffms2-2-30-0 = ["ffms2-2-27-0"]
ffms2-2-31-0 = ["ffms2-2-30-0"]

default = ["ffms2-2-31-0"]

[workspace]
members = ["ffms2-sys"]
